SELECT
    TITLE,
    USED_GOODS_BOARD.BOARD_ID,
    USED_GOODS_REPLY.REPLY_ID,
    USED_GOODS_REPLY.WRITER_ID,
    USED_GOODS_REPLY.CONTENTS,
    TO_CHAR(USED_GOODS_REPLY.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM
    USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE
    USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
    AND USED_GOODS_BOARD.CREATED_DATE >= DATE '2022-10-01'
    AND USED_GOODS_BOARD.CREATED_DATE < DATE '2022-11-01'
ORDER BY
    USED_GOODS_REPLY.CREATED_DATE ASC, TITLE ASC;